src/main/java/cinebox/common/exception/BaseException.java
src/main/java/cinebox/common/exception/ErrorResponse.java
src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/GlobalExceptionHandler.java
src/main/java/cinebox/common/exception/movie/NotFoundMovieException.java
src/main/java/cinebox/common/exception/user/NotFoundUserException.java

- 예외 처리에 대한 기본 구조 생성
- 예시로 NotFoundUserException, NotFoundMovieException 생성

Feat: 예외 처리 기능 추가

---

src/main/java/cinebox/common/enums/MovieStatus.java
src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/movie/DuplicatedMovieException.java
src/main/java/cinebox/controller/MovieController.java
src/main/java/cinebox/dto/request/MovieRequest.java
src/main/java/cinebox/dto/response/MovieResponse.java
src/main/java/cinebox/entity/Movie.java
src/main/java/cinebox/repository/MovieRepository.java
src/main/java/cinebox/service/MovieService.java
src/main/java/cinebox/service/MovieServiceImpl.java

- 중복 영화에 대한 예외 추가
- 영화 등록 시, 영화 상태 비공개로 초기화
- s3 미적용으로 인한 이미지 url에 처리 미구현

Feat: 영화 등록 기능 구현

---

src/main/java/cinebox/controller/MovieController.java
src/main/java/cinebox/repository/MovieRepository.java
src/main/java/cinebox/service/MovieService.java
src/main/java/cinebox/service/MovieServiceImpl.java

> - 모든 영화 목록 조회
> - 영화 목록 조회 시, 이름 순서에 따른 조회와 영화 제목 검색 기능 추가
> - 특정 영화 조회 기능 구현
> - 인증/인가 기능 구현 후 사용자 권한에 따른 조회 범위 설정 필요
>

Feat: 영화 조회 기능 구현

---

src/main/java/cinebox/DataInitializer.java
src/main/java/cinebox/entity/Auditorium.java
src/main/java/cinebox/entity/Seat.java
src/main/java/cinebox/repository/AuditoriumRepository.java
src/main/java/cinebox/repository/SeatRepository.java

> 상영관과 좌석에 대한 데이터 기본 생성
> - "상영관 1\~N", "A1\~J10"
>

Feat: 상영관 및 좌석 데이터 기본 생성

---

src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/GlobalExceptionHandler.java
src/main/java/cinebox/common/exception/movie/MovieDeleteFailedException.java
src/main/java/cinebox/controller/MovieController.java
src/main/java/cinebox/dto/request/MovieRequest.java
src/main/java/cinebox/dto/validation/CreateGroup.java
src/main/java/cinebox/entity/Movie.java
src/main/java/cinebox/service/MovieService.java
src/main/java/cinebox/service/MovieServiceImpl.java

#9 
> - 영화 수정 기능 구현
> - 영화 삭제 기능 구현
> - 같은 DTO 내에서 검증 시점 분리 (등록, 수정)
>

Feat(#9): Edit movie

---

src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/GlobalExceptionHandler.java
src/main/java/cinebox/controller/MovieController.java
src/main/java/cinebox/security/JwtTokenProvider.java
src/main/java/cinebox/security/SecurityConfig.java
src/main/java/cinebox/service/MovieServiceImpl.java

#13
> 기존 Movie CRUD에 사용자 ROLE에 대한 접근 범위 설정
> - Create: only ADMIN
> - Read:
>    - ALL
>       - ADMIN: 모두 조회 가능
>       - USER: UPCOMING, SHOWING 조회 가능
>    - Specific
>      - ADMIN: 모두 조회 가능
>      - USER: UNRELEASED를 제외하고 조회 가능
> - Update: only ADMIN
> - Delete: only ADMIN
>

Feat(#13): movie crud auth

---

src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/review/NotFoundReviewException.java
src/main/java/cinebox/controller/ReviewController.java
src/main/java/cinebox/controller/UserController.java
src/main/java/cinebox/dto/request/ReviewRequest.java
src/main/java/cinebox/dto/response/ReviewResponse.java
src/main/java/cinebox/entity/Review.java
src/main/java/cinebox/repository/ReviewRepository.java
src/main/java/cinebox/security/JwtTokenProvider.java
src/main/java/cinebox/security/PrincipalDetailsService.java
src/main/java/cinebox/security/SecurityConfig.java
src/main/java/cinebox/service/ReviewService.java
src/main/java/cinebox/service/UserService.java

Feature(#18): review CRUD

---

src/main/java/cinebox/CineboxApplication.java
src/main/java/cinebox/dto/response/KmdbResponse.java
src/main/java/cinebox/dto/response/KobisMovieListResponse.java
src/main/java/cinebox/entity/Movie.java
src/main/java/cinebox/repository/MovieRepository.java
src/main/java/cinebox/service/MovieBatchService.java

> #12 
- 매일 0시 30분
- '개봉 예정' 상태이며, 개봉일이 당일과 같거나 이전인 영화의 상태 변경 (UPCOMING -> SHOWING)
- 매주 월요일 00시
- KOBIS API: 영화 목록 조회
- KMDB API: 영화 상세 조회 (포스터, 배우, 줄거리, 러닝타임, 관람등급)
- DB에 영화 존재 시, KMDB API 호출하지 않음 (영화 제목, 개봉일 비교)
- 매년 12월 15일 01시
- 다음 연도 영화 목록 조회 및 상세 조회
>

Feat(#12): Batch Service를 통한 영화 등록

---

src/main/java/cinebox/controller/ScreenController.java

> #39 
> hasRole을 통해 ADMIN 유저만 Screen에 대한 편집을 가능하게 하도록 구현
>

Feat(#39): Screen 편집 권한 설정

---

src/main/java/cinebox/dto/response/ReviewResponse.java
src/main/java/cinebox/dto/response/TicketResponse.java

#59 
- ReviewResponse: Identifier, createdAt 추가
- TicketResponse: BookingStatus 추가
>

Refactor(#59): Response 필드 추가

---

src/main/java/cinebox/controller/MovieLikeController.java
src/main/java/cinebox/dto/response/MovieResponse.java
src/main/java/cinebox/entity/Movie.java
src/main/java/cinebox/entity/MovieLike.java
src/main/java/cinebox/entity/User.java
src/main/java/cinebox/repository/MovieLikeRepository.java
src/main/java/cinebox/service/MovieLikeService.java
src/main/java/cinebox/service/MovieLikeServiceImpl.java

#62 
- 좋아요 토글을 통한 좋아요 등록 및 취소 구현
- 본인이 좋아요를 누른 영화 목록 조회
>

Feat(#62): 좋아요 기능 구현

---

src/main/java/cinebox/controller/ScreenController.java
src/main/java/cinebox/dto/response/ScreenResponse.java
src/main/java/cinebox/repository/ScreenRepository.java
src/main/java/cinebox/service/ScreenService.java
src/main/java/cinebox/service/ScreenServiceImpl.java

Feat(#69): 영화별 상영 목록 조회 기능 구현

---

src/main/java/cinebox/controller/AuditoriumController.java
src/main/java/cinebox/dto/response/AuditoriumResponse.java
src/main/java/cinebox/service/AuditoriumService.java
src/main/java/cinebox/service/AuditoriumServiceImpl.java

Feat(#77): 상영관 목록 조회 기능 구현

---

pom.xml
src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/movie/S3ServerException.java
src/main/java/cinebox/domain/movie/controller/MovieController.java
src/main/java/cinebox/domain/movie/dto/MovieRequest.java
src/main/java/cinebox/domain/movie/service/MovieService.java
src/main/java/cinebox/domain/movie/service/MovieServiceImpl.java
src/main/java/cinebox/domain/movie/service/S3Service.java
src/main/java/cinebox/domain/movie/service/S3ServiceImpl.java
src/main/java/cinebox/security/config/S3Config.java

#56 
- 영화 생성 및 수정 시, s3에 이미지를 저장하며 해당 url을 db에 저장
- s3에 저장되는 파일명로 영화 제목, 개봉일을 사용하므로 유효성 검사 진행
>

Feat(#56): 영화 포스터 이미지 S3에 저장

---

src/main/java/cinebox/common/exception/ExceptionMessage.java
src/main/java/cinebox/common/exception/auditorium/AlreadyExistAuditoriumException.java
src/main/java/cinebox/common/runner/DataInitializer.java
src/main/java/cinebox/domain/auditorium/controller/AuditoriumController.java
src/main/java/cinebox/domain/auditorium/dto/AuditoriumRequest.java
src/main/java/cinebox/domain/auditorium/entity/Auditorium.java
src/main/java/cinebox/domain/auditorium/repository/AuditoriumRepository.java
src/main/java/cinebox/domain/auditorium/service/AuditoriumService.java
src/main/java/cinebox/domain/auditorium/service/AuditoriumServiceImpl.java

#90 
- 상영관 생성 (좌석 행과 열을 입력받아 생성)
- 상영관 이름 입력 필수
- A~Z 까지의 행 입력 필수
- 1~30까지의 열 입력 필수
- 상영관 이름 수정
- 상영관 이름 입력 필수
>

Feat(#90): 상영관 생성 및 수정 기능 구현

---

Dockerfile

> 새로운 브랜치 feature/add-dockerfile 생성
> 프로젝트 루트 디렉토리에 Dockerfile 추가
> Dockerfile 설정이 적절한지 확인 부탁드립니다.

CI(#72): Create Dockerfile

---

src/main/java/cinebox/domain/auditorium/dto/AuditoriumResponse.java
src/main/java/cinebox/domain/booking/controller/BookingController.java
src/main/java/cinebox/domain/booking/service/BookingService.java
src/main/java/cinebox/domain/booking/service/BookingServiceImpl.java
src/main/java/cinebox/domain/screen/dto/AuditoriumScreenResponse.java

#97
- Response 상영관 좌석 수 필드 추가
- AuditoriumResponse
- AuditoriumScreenResponse
- 특정 사용자에 대한 예매 목록 조회 기능 구현
- 관리자만 접근 가능
>

Feat(#97): 프론트 요구사항 반영

---

src/main/java/cinebox/batch/service/MovieBatchService.java
src/main/java/cinebox/common/enums/RatingGrade.java

Refactor(#73): Batch Service 레포지토리 분리

---

src/main/java/cinebox/domain/auditorium/dto/AuditoriumRequest.java
src/main/java/cinebox/domain/auditorium/service/AuditoriumServiceImpl.java

#106 
AuditoriumRequest 필드명 변경 (name -> auditoriumName)
>

Refactor(#106): 프론트 Request에 맞춰 필드명 수정

---

src/main/java/cinebox/domain/auditorium/controller/AuditoriumController.java

#108 
PutMapping에 매핑되어야 할 auditoriumId가 누락되어 404 에러가 발생하고 있어,
누락된 매핑 주소 추가
>

Fix(#108): 매핑 주소 누락 수정

---

src/main/java/cinebox/domain/auth/service/AuthServiceImpl.java
src/main/java/cinebox/security/jwt/JwtTokenProvider.java

Fix(#110): 로그아웃 시 redis에서 토큰 삭제

---

src/main/java/cinebox/domain/auditorium/controller/AuditoriumController.java
src/main/java/cinebox/domain/auditorium/service/AuditoriumServiceImpl.java
src/main/java/cinebox/domain/auth/controller/AuthController.java
src/main/java/cinebox/domain/auth/service/AuthServiceImpl.java
src/main/java/cinebox/domain/booking/controller/BookingController.java
src/main/java/cinebox/domain/booking/service/BookingServiceImpl.java
src/main/java/cinebox/domain/like/controller/MovieLikeController.java
src/main/java/cinebox/domain/like/service/MovieLikeServiceImpl.java
src/main/java/cinebox/domain/movie/controller/MovieController.java
src/main/java/cinebox/domain/movie/service/MovieServiceImpl.java
src/main/java/cinebox/domain/movie/service/S3ServiceImpl.java
src/main/java/cinebox/domain/payment/controller/PaymentController.java
src/main/java/cinebox/domain/payment/service/PaymentServiceImpl.java
src/main/java/cinebox/domain/review/controller/ReviewController.java
src/main/java/cinebox/domain/review/service/ReviewServiceImpl.java
src/main/java/cinebox/domain/screen/controller/ScreenController.java
src/main/java/cinebox/domain/screen/service/ScreenServiceImpl.java
src/main/java/cinebox/domain/seat/controller/SeatController.java
src/main/java/cinebox/domain/seat/service/SeatServiceImpl.java
src/main/java/cinebox/domain/user/controller/UserController.java
src/main/java/cinebox/domain/user/service/UserServiceImpl.java

Feat(#111): 로그 추가

---

src/main/java/cinebox/domain/auth/service/AuthServiceImpl.java
src/main/java/cinebox/domain/user/repository/UserRepository.java
src/main/java/cinebox/domain/user/service/UserServiceImpl.java

Feat(#118): 플랫폼 별 회원가입 유저 검증 분리

---

pom.xml

#122 
- Spring Boot Actuator 의존성 추가
- Prometheus가 actuator 메트릭을 사용할 수 있도록 의존성 추가
>

feat(#122): Actuator 의존성 추가

---

.github/workflows/deploy.yml
pom.xml

#122 
- Spring Boot Actuator 추가
- Prometheus 연결 테스트 완료
- Grafana Dashboard 확인 완료
-> 배포
>

Feat(#122): Actuator 추가

---

pom.xml
src/main/resources/logback-spring.xml

#125 
- 로그 포맷을 JSON으로 변경
- application.properties 에 설정 추가 필요
```
logging.config=classpath:logback-spring.xml
```
>

Feat(#125): JSON으로 로그 포맷 변경

---

.github/workflows/deploy.yml

Feat: 로그 포맷 변경

---

.github/workflows/deploy.yml
src/main/java/cinebox/common/config/CookieConfig.java
src/main/java/cinebox/common/config/FilterConfig.java
src/main/java/cinebox/common/config/RedisRepositoryConfig.java
src/main/java/cinebox/common/config/RequestMethodLoggingFilter.java
src/main/java/cinebox/common/config/RestTempateConfig.java
src/main/java/cinebox/common/config/S3Config.java
src/main/resources/logback-spring.xml

#128 
로그에 Http Method를 출력함으로써 로그 분석 활용도를 높임
>

Feat(#128): 로그에 Http Method 추가
